### ISSUE TITLE
Aplikacia: Registracia do registracia Konecnych Uzivatelov Vyhod

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#218]
Toto je dobry kandidat na navod/aplikaciu - je to povinne pre vsetky firmy do konca roka. Riesieme primarne jednoduche pripady (jeden/dvaja konatelia, nie obskurne pripady).

Treba vymysliet flow, porobit staticke html, pridat mozno integraciu na autoform/datahub (tahanie dat o firmach, konateloch) a vygenerovanie ziadosti. 

Info k procesu:
- http://rybanova.sk/zapis-konecneho-uzivatela-vyhod-do-obchodneho-registra-postup-krok-za-krokom/
- https://www.slovensko.sk/sk/oznamy/detail/_zapis-udajov-o-konecnom-uzivat

TODOs
- [ ] zistit co vieme/nevieme vytiahnut z API
- [ ] zistit ako to vieme a budeme podavat (@jsuchal)
- [ ] rozhodnutie ci ideme robit aj zmenu alebo len prvotny zapis - to trochu meni flow (@HanaBene )
- [ ] legal check
- [ ] keywords + reklama na adwords

**Comment by jsuchal** [comment]
@michalrohacek256 tuto budeme riesit vsetko ohladom tejto appky.

**Comment by jsuchal** [comment]
@michalrohacek256 spravil takuto analyzu prvotnu https://1drv.ms/o/s!AgNJVf9fjhOwhigYBMNvv5XRZ15A

cc @HanaBene

**Comment by HanaBene** [comment]
nie je moznost sustredit sa teraz na zapis a po 1.1. to prerobit na zmenu udajov? (vsetci uz budu zapisani) Znamenalo by to zasadne zmeny pre ten flow a implementaciu samotnu?

**Comment by jsuchal** [comment]
Dizajn manual (nie final ale draftove navrhy)
- https://github.com/alphagov/govuk-design-system-backlog/issues/21
- http://hmrc.github.io/assets-frontend/patterns/add-to-a-list/index.html (toto je asi celkom presne ono aj ked ten pridavaci flow je fakt ukecany)

**Comment by ondond** [comment]
aplikacia od nas: https://konecneuzivatel.sk (len zapis)

**Comment by jsuchal** [comment]
@HanaBene toto mozeme asi zavriet, ze?
