### ISSUE TITLE
Zapis RC statutarov do ORSR

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#485]
Do 30.9. maju statutari zapisat do ORSR rodne cisla (ak ich nezapisali automatom - je to vyse 140k ludi). Je to velmi podpobny proces ako zapis do registra KUV.

idea je nasledovna: 
- zadam ico/meno firmy - autoform (alebo login cez eid/mid a nacitame sami?)
- natiahnu sa statutari. doplnim RC
- mam vyplneny formular a viem ho poslat cez slovensko.sk sluzbu  (bacha je tam dost priloh)
- pripadne to vieme poslat cez nasu integraciu (bacha, treba podpisovat, mozno aj viac statutarov!)

https://www.justice.gov.sk/sluzby/obchodny-register/zmeny-k-1-10-2020/doplnenie-identifikacnych-udajov-pre-jednotlive-pravne-formy/

Sem spisujeme pripady ktore skusame na fixe:
- [ ] hany.sk - bratislava ako obec (mimo formularoveho ciselnika ale v oficialnom ciselniku) - zatial jedine preslo dalej - cakame na zapis
- [ ] swiss re corporate (zahranicna pravnicka osoba) - nepreslo vid koment dole
- [ ] kombinacia FO+PO spolocnici: Gerulata, s.r.o., IČO: 43946780 (fail - nenaslo v orsr)
- [ ] Vrchovský, s. r. o., IČO: 45983844 (dve fo - vsetko by malo byt podla ciselnika) - nenaslo v orsr

**Comment by jsuchal** [comment]
https://www.efektivnejsie.sk/blog/legislativa/nova-zakonna-povinnost-zapisat-rodne-cislo-do-obchodneho-registra/

**Comment by jsuchal** [comment]
https://www.youtube.com/watch?v=MNfP2hcRycA toto je fajn navod ako to vyplnit cele.

Trochu sa mi tam nezda, ze musis vyplnat aj vklady a tieto veci. To je fakt divne.

**Comment by crutch** [comment]
Toto je zaujimava info v tom video navode

<img width="670" alt="image" src="https://user-images.githubusercontent.com/119724/175766285-3d926089-f211-4fbc-9ca1-6a93d73780cd.png">

- podava to PO, ale podpisuje konatel
- ak je zaroven aj spolocnikom a meni len svoje udaje, tak je bez prilohy
- inak potrebuje splnomocnenie a cestne vyhlasenie, vraj notarsky overene (sa asi da nahradit KEPom)

Myslim, ze firma s viacerymi spolocnikmi, ktori su vsetci konatelia to kludne mozu urobit na tri podania...

**Comment by crutch** [comment]
v pripade, ze je spolocnikom PO, tak orsr aj tak ukazuje na webe, ze "Osoba nema zapisane vsetky pozadovane udaje". Ale PO nema RC, tak to si tam ma PO dat zapisat?

<img width="675" alt="image" src="https://user-images.githubusercontent.com/119724/175773503-10179b70-4453-4b38-b188-5f7ac80ffbf3.png">

**Comment by TomasMakan** [comment]
Figma prototyp
https://www.figma.com/proto/52FcEfWSNhnufVezLqDw9G/navody.digital?node-id=11122%3A3315&scaling=min-zoom&page-id=11122%3A3314&starting-point-node-id=11122%3A3315

**Comment by TomasMakan** [comment]
Diagram
https://drive.google.com/file/d/1CgxTLz2qqa_6JVFHapqLu4jXZtJfw1I5/view?usp=sharing

**Comment by TomasMakan** [comment]
Otázky:
- vieme sa dostať k údajom, ktoré sú teraz zapísané (verejné aj neverejné), aby sme vedeli spraviť výmaz?
- Ktoré všetky číselníky sa pri tejto časti používajú?
- ako veľmi sa odlišujú údaje na výmaz a zápis v závislosti od typu spoločnosti?
- štatistiky početnosti jednotlivých typov spoločností, koľko % údajov je ok v jednotlivých spoločnostiach?
- Vieme ponúknuť iba zmenu (výmaz + zápis) pre FO/PO, ktoré už sú v ORSR?
- pre zjednodušenie nám vychádza, že napr. spoločníci/ konatelia by pre rýchlosť mali spraviť podania zvlášť (každý konateľ za seba). Je táto informácia správna?

**Comment by jsuchal** [comment]
Mame vysledok.

- Prevažná časť  notifikácii o potrebe doplnenia identifikačných údajov sa týkala právnej formy spoločnosť s ručením obmedzeným ( vyše 140 000). Ostatné právne formy boli zastúpené v rozsahu cca 1500 a nižšie.

- Odkonzultovali sme „navrhovateľa“ v zápisovom formulári – má by to byť právnická osoba, ktorá navrhuje zápis zmeny.

**Comment by jsuchal** [comment]
Podla mna uz mame asi vsetko co sme potrebovali. Este mi nie je uplne zrejmy postup ked mam v ORSR zlu adresu (napr. moj pripad). V takomto pripade sa zapisuje nova adresa (a bude to bez poplatku) alebo treba spravit normalne podanie zmenit adresy a pridat RC a takto to zbehne?

**Comment by jsuchal** [comment]
Podla dohody sem pisem nejake scenare, ktore by sme mali podporovat:

1. Konatel slovenskej firmy, co nema zapisane vsetko potrebne. Zadava RC, ICO pre firmy(spolocnikov) 
2. Konatel slovenskej firmy, co nema zapisane vsetko potrebne avsak je tam osoba/firma zahranicna (zadavaju sa ine identifikatory)
3. Konatel firmy, co ma zapisane vsetko potrebne - tu ho len treba upozornit, ze vyzera ze ma vsetko v poriadku a nech sa prihlasi na newsletter pre firmy ak nie je.

Zatial sa sustredme na SRO, neviem nakolko sa to lisi pre ine formy.

Texty:
- treba pripravit navod a dobre vysvetlit aj flow viacnasobneho podpisovania.
- treba pripravit emaily ktore sa poslu kde bude priloha co treba poslat. taktiez treba dobre vysvetlit ze co treba podpisat (aj formular aj prilohu)

Nedoriesene:
- podla prveho vyjadrenia MSSR to vyzera tak, ze ti co nemaju uz dnes zapisane dobre trvaly pobyt alebo nieco maju zle v ORSR, tak **musia** ist platenym sposobom. Formular je rovnaky, len sa tam zaskrtne nieco ine a vyplnaju sa nove udaje. Ci k tomu treba nejake prilohy neviem. Idem to vyskusat aj tak.

cc @TomasMakan @luciajanikova

**Comment by jsuchal** [comment]
Na co si dat bacha pri vyplnani podania.

- Prilohy su povinne (sa tvaria) - ja som tam napisal poznamku, ze formular je nevalidny a teda nedavam ziadne prilohy.
- Treba tam zaskrtnut vlavo checkbox pri sekcii (!!!), ze toto je ta zmena.
- Podpisat dsignerom java sa mi to nepodarilo - podpisal som aj formular aj prilohovy formular cez podpisuj.sk

Po uspesnom podani pride toto:
![image](https://user-images.githubusercontent.com/26342/183491150-fcee1cf7-54ca-4e10-ade7-52ef36d4ad79.png)

**Comment by tajovic** [comment]
K scenaru 1 a 2:
To ICO (ine identifikatory) sa tam zadava aj mimo vyhladavania firmy? Ako to funguje?

**Comment by jsuchal** [comment]
@tajovic ked je spolocnik firma, tak musis vyplnit jej identifikacne udaje. Je to tato cast formulara:
![image](https://user-images.githubusercontent.com/26342/183850096-492dbcc6-be0b-4ad2-a994-112cd9f65fcb.png)
https://www.justice.gov.sk/eSluzby/_layouts/FormServer.aspx?XsnLocation=/FormServerTemplates/FUZS.xsn#


Btw dalsi krok v procese je pridelenie sudcu/vsu - dosla mi notifikacia dalsia (posielaju aj do schranky aj na email)
- 
![image](https://user-images.githubusercontent.com/26342/183849844-968483e0-c82f-4c48-b033-18b14e10784c.png)

**Comment by tajovic** [comment]
@jsuchal cize pri fyzickej osobe doplni clovek iba RC, pri pravnickej aj dalsie udaje a pri osobe zo zahranicia zas nejake ine udaje? Cize je to vzdy iba ina seria info na doplnenie podla toho o aku osobu sa jedna?

**Comment by luciajanikova** [comment]
@jsuchal vieme o tom, ci existuje v tom ich API moznost ziskat info o tom, ci pre konkretnych spolocnikov chybaju identifikacne udaje?

**Comment by jsuchal** [comment]
> @jsuchal cize pri fyzickej osobe doplni clovek iba RC, pri pravnickej aj dalsie udaje a pri osobe zo zahranicia zas nejake ine udaje? Cize je to vzdy iba ina seria info na doplnenie podla toho o aku osobu sa jedna?

Ano.



> @jsuchal vieme o tom, ci existuje v tom ORSR API moznost ziskat info o tom, ci pre konkretnych spolocnikov chybaju identifikacne udaje?

Ano existuje, je to priamo na www.orsr.sk @crutch k tomu robil parser v inom PR/branch.  https://github.com/slovensko-digital/navody.digital/compare/master...orsr-parser bez hanby kopiruj.

**Comment by tajovic** [comment]
Ake vsetky udaje pri pravnickej osobe a pri zahranicnej osobe je mozne doplnit zadarminko?

**Comment by tajovic** [comment]
Potrebujem (neviem ci uz niekde je) spisane vsetky udaje k jednotlivym scenarom, aby som ich vedel hodit do mockupu.

**Comment by jsuchal** [comment]
Od kamosa:

_Ahoj,

de lege by sa mali dopĺňať len chýbajúce údaje, ale v praxi keď je takáto situácia, tak tam buchnem rovno aj zmenu bydliska a prechádza to bez poplatku… Na jednej strane ten zákon hovorí o doplnení údajov, na druhej o zosúladení, čiže si myslím, že to nie je nejak nemorálne…

Čo sa týka prílohy, prikladám tam vyhlásenie osoby o tom, že má trvalý pobyt taký a taký. Zákon nestanovuje konkrétnu prílohu. Na druhej strane stanovuje, že zápis má vyplývať z predložených listín, čiže pro forma tam dávam taký papier, aby nikto nefuchtloval.

Pre úplnosť, skôr si myslím, že postup, kedy by sa to nezosúladilo, by bol viac riskantný z hľadiska odmietania zápisov. LEBO: “[Registrový súd zabezpečuje, aby sa pri zapisovaní údajov do obchodného registra používali aktuálne hodnoty referenčných údajov.](https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/2003/530/#paragraf-2.odsek-7)”

Vyššie uvedené sa týka BA registra, v iných som takú situáciu nemal, postup sa môže líšiť._

**Comment by TomasMakan** [comment]
Takže pripraviť verziu iba na RČ aj na ostatné dáta a skúsiť z MSSR a súdov získať "nepriestreľnú" odpoveď, čo vlastne chcú?

**Comment by jsuchal** [comment]
@TomasMakan ano vidim to tak. 

@tajovic ked kuknes ten formular tak z toho to nevies vycitat?

**Comment by jsuchal** [comment]
Info z MSSR - zalezi na sudcoch, ale podla nich by nemali zapisovat nic ine ako RC/identifikatory.

- Funkcia na upravu trvaleho pobytu automaticky nie je implementovana (imho porusenie zakona egov)
- Ako priloha nevieme co uplne treba, riadil by som sa tym hore od kamosa.

**Comment by tajovic** [comment]
A teda ako budeme postupovat? Vidim tieto moznosti:

- ofiko budeme cisto iba dopisovat chybajuce udaje
- ofiko budeme dopisovat aj platene udaje ale budeme o tom informovat
- budeme alibisticky a povieme, ze meh.. mozno to prejde mozno nie

**Comment by TomasMakan** [comment]
> A teda ako budeme postupovat? Vidim tieto moznosti:
> 
> * ofiko budeme cisto iba dopisovat chybajuce udaje
> * ofiko budeme dopisovat aj platene udaje ale budeme o tom informovat
> * budeme alibisticky a povieme, ze meh.. mozno to prejde mozno nie

Pošlite toto a ak vám to neprejde, tak tu máte lite verziu (iba rodné číslo), alebo pošlite znova tú pôvodnú a zaplaťte... :D

**Comment by jsuchal** [comment]
Zda sa, ze este nejaky piatok bude trvat kym sa to zaimplementuje cize je mozne ze ludia budu musiet nahlasovat zmeny do ORSR. (Toto je na separe debatu pravnikov MIRRI-MSSR asi, ci to je porusenie zakona o egov)

Formular je vsak rovnaky aj ked robis (lubovolne) zmeny, len to bude s poplatkom, ako pise @TomasMakan - myslim, ze tam je rozdiel len v tom, ze zaskrtnes jeden chechbox inak (pusti sa poplatkovy flow nasledne). 

Navrhujem napisat tym 8 sudom, aby sme mali nejake vyjadrenie ofiko - ak nam neodpisu len nieco "postupujeme podla zakona".

Zatial mi to vychadza asi tak, ze chceme podporu aj pre zmenu mena/adresy.

**Comment by tajovic** [comment]
Mame zbuchany prototyp na diskusiu. Nakolko rozdiel vo FO vs PO a obcianstvo je iba otazka inputov, nezakomponovali sme to zatial v prototype. Taktiez sme tam dali ukazku doplnania udajov iba jednej osoby. Prototyp viete kedykolvek restartnut pismenom R.

[Flow doplnenia informacii](https://www.figma.com/proto/52FcEfWSNhnufVezLqDw9G/navody.digital?page-id=11122%3A3314&node-id=11472%3A88777&viewport=1561%2C-1040%2C0.19&scaling=min-zoom&starting-point-node-id=11472%3A88777&show-proto-sidebar=1&hide-ui=1) (ilustruje FO so Slovenskym obcianstvom).
[Flow bez nutnosti doplnenia](https://www.figma.com/proto/52FcEfWSNhnufVezLqDw9G/navody.digital?page-id=11122%3A3314&node-id=11503%3A90081&viewport=1561%2C-1040%2C0.19&scaling=min-zoom&starting-point-node-id=11503%3A90081&show-proto-sidebar=1&hide-ui=1) 

Pozrite na to prosim a napiste co si myslite x)

- Je to ok flow?
- Je to podla vas zrozumitelne (budeme to ofc testovat)?
- Chyba tam nieco?
- Je to realizovatelne?

**Comment by tajovic** [comment]
Pri cloveku asi nevieme urcit ci je obcan slovenska na zaklade adresy (moze byvat v BA ale nemat RC. Ale pri firme by to mohlo ist, nie? Ked ma adresu na slovensku bude mat ICO a ked nema adresu na slovensku, bude mat ten vseobecny string. Mylim sa?

**Comment by jsuchal** [comment]
@tajovic flow 1 mi pride ok aj ked pre vacsinu to bude vela klikania zvazujem, ze tam ako default dat ze to je fyzicka osoba a pod/pri kazdej checkbox "ano ide o obcana sr" a druhy "nie ide o nieco ine" a az potom vyberas. hm? dokonca budeme mozne vediet rozlisit nejake pripady automatom mozno. 

na prvy pohlad nevidim velmi nic co by chybalo - predpokladam, ze pre zahranicne firmy / osoby budu len ine inputy.

**Comment by jsuchal** [comment]
> Pri cloveku asi nevieme urcit ci je obcan slovenska na zaklade adresy (moze byvat v BA ale nemat RC. Ale pri firme by to mohlo ist, nie? Ked ma adresu na slovensku bude mat ICO a ked nema adresu na slovensku, bude mat ten vseobecny string. Mylim sa?

Ak tam je nieco ako "slovenska republika" tak by to slo. ale taketo detekcie vychytavky si nechajme ako nice to have.

**Comment by tajovic** [comment]
> flow 1 mi pride ok aj ked pre vacsinu to bude vela klikania zvazujem, ze tam ako default dat ze to je fyzicka osoba a pod/pri kazdej checkbox "ano ide o obcana sr" a druhy "nie ide o nieco ine" a az potom vyberas. hm? dokonca budeme mozne vediet rozlisit nejake pripady automatom mozno.

Ten automat by bola velka pomoc. Naozaj sa neda urcit aspon ta PO / FO? Napriklad podla fieldov, ktore su v OSRS? FO ma meno a priezvisko, a PO ma nazov? Je mozne kuknut na nejaku vzorku z toho obchodneho registra nech skusime najst patterny?

**Comment by jsuchal** [comment]
Zapis uspesne prebehol, na dalsi den sa mi v orsr zjavili "zelene fajky", do schranky som dostal novy vypis z ORSR a vselico.

**Comment by jsuchal** [comment]
Swiss re corporate:

![image](https://user-images.githubusercontent.com/26342/189399284-87c0042f-34a1-43f9-8fb7-e31a382513e7.png)

toto bude u nich nejaky bordel lebo to je dobre https://orsr.sk/vypis.asp?ID=400386&SID=2&P=1

cc @luciajanikova (hore pisem pripady co posielam na fix)

**Comment by luciajanikova** [comment]
V pripade spolocnikov s rovnakym menom pridame vklad, vyzera to takto:
![image](https://user-images.githubusercontent.com/43437253/189484425-2a5013a5-900f-4e26-ab8d-e24a5c00a616.png)
Nejake namietky? @jsuchal @tajovic

**Comment by jsuchal** [comment]
@luciajanikova toto mozeme zatvorit uz nie?
